name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build from template
      run: npm run-script build

    - name: Deploying to gh-pages
      run: npm run deploy
