name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages in packages.json
      run: npm install

    - name: Build from template
      run: npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
